EMAIL_ADDRESS = "anvaya661@gmail.com"
EMAIL_APP_PASSWORD = "sbndyjidrwcpuzxi"

GEMINI_API_KEY_1 = "AIzaSyAD65ZnEFpDIWcnGv4MJ65FwFFFvtvF_wU"

GEMINI_API_KEY_2 = "AIzaSyAE2azLMkGaEQudkdVGP8fMTrJ1Gz1J7pk"

[firebase]
  
  type= "service_account"
  project_id= "anvaya-44d58"
  private_key_id= "ff9c8789a384618622cad6516d1f3e16cfa96728"
  private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6YjZ1JwE9dqcp\n7el08Nsnww6UF9AQNheV9pkns4mYNZw9LuLCocIqTDvA0Sg8ZkDePdNxPRMNaZr7\n5TfgWy8GvrSE55VcbXT0EbDYbEsAdGH0I3G4VKnUH+WdS/0arCzA7Yj9ZK2F5pLY\nbSwkAYOjeOPuE0+VVAWiQdtGjbDSIbaHoQ6LbhmsxZJam9/Rqqq4945wM4bJKOPn\n6nZFzdu8gXihJcO0qZ3Ny7yj8mK8ilTkMpndW87UJln6NpZgKnoopUEtpPINR+8m\nuU4whKa6rxX6MI8A3hECKt8ZfMuXxy5xy6OLH8zFFLsuDGISLg7S5V/bTXjsVRS3\n0x5zWjyZAgMBAAECggEAAc04PIqreuYeOIwJsS0w2SIMDodqZfW35aW0FkuofVWr\nVHYTEBGTOGhzPWpoKqlMYDmVxSbze7I1ItE06JDJFBYc1ZoNeg6+zisrm/P0B6WY\nWs1K6J6844WJaStWX38hkZ3aMKTb/orbiYcIobJ4DMj63w7FuqpMwaREU9rDxkwz\n4yufXAn8A3Zsa8iC5ZOIYb2fboNmSVhJr6JKoDZYkbr79JR3nSgWIJ6ZXHKorl9f\ni3/IKiM7435deWNyag7i6/vkK1SXOCrVdXUJn5eL1rYFwCjGY1RXoTDDjT+35Alo\nd8cNcugGYW0B+jbKaQ91r9ERuqargkRRyL85sbiUdwKBgQDv2PrkyInd+dP8QeDP\nnaU2YRsgvLepT8Zgc4MTWOFJHtJMtARaDfTVBArnIq7wB0GsVQWgAdY2Vg1g/PXh\njfguoqhxjdEcy+6TjABy9P6n0hVt04aJCKGzqmCXFgDc2+ZbLE2mUrGAPk5Xw7Zh\njOIk/4iMDbIATCGnZIwvOcIsEwKBgQDG74D5NBqQYVcQQSshI+K3648syZNiU151\nvywUhxnrsKfSl+VTLGI7eG/RpZ/vkElMReaYgDw9eifv/xplaZ0wTHps7u1FffFz\nu6h1JNM1KBnF+zZuL7UBmRiUYlbmjHouUmpMcQQbCyoKBMwm+ITKzMshGZ6jsDt9\nDvrI21OyIwKBgAdzgjfhUwcmX8OSeF161EsgMSuPMVV9OPh+HjBXrogLARWI8imq\nDVUgzwXnOfATCaNE8OvLotAFVF0S/sCHHJK2Uu1ULo7qdvr2en0Xx2GHUUscKy3O\nqtdeD6oh8Nzrp/hlI/Rq1UDarqxjVCMrsUrc9W0Eb+c6dkExCnndHX8pAoGBAKoo\nyJ/gImym5iqgI30ITe/VjDTaArgS6XQ73j98w/4mr5XhmSVIjImj3blsOt5WA2w7\nSh/daCmJqEmPYgumh+59LCarQ8ayEGpW9KOmqQYJ0+nVk9wx8Fh6lFyvtPck54lh\ns0zJSqK7LO0+50TaQ/OXspQQbvJCVtAElRxjBjcTAoGATp46lC77597x58+GO6i8\nHHK30C55eSpy9Om59V3Mwp1vL50LVGiPYEdHy1x6pl1V1ej220cosNR9adXgFsE6\nS8vVeSAIqqU2+4PVflBfYgHDi4jupo0huvrRtpRnW10SHoZU+FezsmlkHWMxGvh8\nKfIw5S5xvKtAChSmfuFJLY8=\n-----END PRIVATE KEY-----\n"
  client_email= "firebase-adminsdk-fbsvc@anvaya-44d58.iam.gserviceaccount.com"
  client_id= "104733580984373956109"
  auth_uri= "https://accounts.google.com/o/oauth2/auth"
  token_uri= "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40anvaya-44d58.iam.gserviceaccount.com"
  universe_domain= "googleapis.com"


